//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Servicio
    {
        public int IdServicio { get; set; }
        public string IdCliente { get; set; }

        [Required]
        public string Ciudad { get; set; }

        [Required]
        public string Barrio { get; set; }

        [Required]
        public string Direccion { get; set; }

        [Required]
        [Display(Name = "Precio Venta")]
        public Nullable<double> PrecioVenta { get; set; }

        [Required]
        [Display(Name = "Nombre del Inmueble")]
        public string Area { get; set; }
        public string Estrato { get; set; }
        public Nullable<double> PrecioServicio { get; set; }
        public string Caracteristicas { get; set; }
    }
}
