//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ServicioComision:Servicio
    {
        
        public string EmailS { get; set; }

        [Required]
        [Range(1, 100)]
        [Display(Name = "Porcentaje Comisión (%)")]
        public Nullable<double> PorcentajeComision { get; set; }
        public Nullable<double> TotalComision { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
