//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.ServicioComision = new HashSet<ServicioComision>();
            this.ServicioHost = new HashSet<ServicioHost>();
        }
    
        public int IdUsuario { get; set; }


        //[EmailAddress(ErrorMessage = "Dirección Invalida")]
        public string Email { get; set; }

        public string Password { get; set; }

        [Display(Name = "Confirm new password")]
        public string PasswordSalt { get; set; }

        
        public string Nombre { get; set; }

        
        public string Apellido { get; set; }

        
        public string TelefonoFijo { get; set; }

        
        [Display(Name = "Telefono Celular")]
        public string TelefonoCellular { get; set; }

        
        [Display(Name = "Dirección")]
        public string Direccion { get; set; }

        
        public string Ciudad { get; set; }

        [Display(Name = "Rol")]
        public string PerfilU { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual ICollection<ServicioComision> ServicioComision { get; set; }
        public virtual ICollection<ServicioHost> ServicioHost { get; set; }
    }
}
